use sys;
CREATE TABLE IF NOT EXISTS Exemplo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    idade INT NOT NULL
);
ALTER TABLE Exemplo
ADD COLUMN DataCriacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN DataAlteracao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

select *
from Exemplo;